# **Problem-1**

In [1]:
import pandas as pd


df = pd.read_csv("Problem-1.csv")
print(df)

   Height  Weight  Age  Grip_strength Frailty
0    65.8     112   30             30       N
1    71.5     136   19             31       N
2    69.4     153   45             29       N
3    68.2     142   22             28       Y
4    67.8     144   29             24       Y
5    68.7     123   50             26       N
6    69.8     141   51             22       Y
7    70.1     136   23             20       Y
8    67.9     112   17             19       N
9    66.8     120   39             31       N

# **CLEAN DATA**

In [2]:
import pandas as pd

df = pd.read_csv("Problem-1.csv")

df["Height_m"] = df["Height"] * 0.0254
df["Weight_kg"] = df["Weight"] * 0.45359237

df["BMI"] = (df["Weight_kg"] / (df["Height_m"] ** 2)).round(2)

def age_group(age):
    if age < 30:
        return "<30"
    elif 30 <= age <= 45:
        return "30–45"
    elif 46 <= age <= 60:
        return "46–60"
    else:
        return ">60"

df["AgeGroup"] = df["Age"].apply(age_group)

df["Frailty_binary"] = df["Frailty"].map({"Y": 1, "N": 0}).astype("int8")

df.to_csv("clean_frailty_data.csv", index=False)

df.head()

,Height,Weight,Age,Grip_strength,Frailty,Height_m,Weight_kg,BMI,AgeGroup,Frailty_binary
0,65.8,112,30,30,N,1.67132,50.802345,18.19,30–45,0
1,71.5,136,19,31,N,1.81610,61.688562,18.70,<30,0
2,69.4,153,45,29,N,1.76276,69.399633,22.33,30–45,0
3,68.2,142,22,28,Y,1.73228,64.410117,21.46,<30,1
4,67.8,144,29,24,Y,1.72212,65.317301,22.02,<30,1

# **A.Unit Standardization**

In [3]:
import pandas as pd


df = pd.read_csv("Problem-1.csv")
df['Height_m'] = df['Height'] * 0.0254
df['Weight_kg'] = df['Weight'] * 0.45359237
print(df[['Height', 'Weight', 'Height_m', 'Weight_kg']])

   Height  Weight  Height_m  Weight_kg
0    65.8     112   1.67132  50.802345
1    71.5     136   1.81610  61.688562
2    69.4     153   1.76276  69.399633
3    68.2     142   1.73228  64.410117
4    67.8     144   1.72212  65.317301
5    68.7     123   1.74498  55.791862
6    69.8     141   1.77292  63.956524
7    70.1     136   1.78054  61.688562
8    67.9     112   1.72466  50.802345
9    66.8     120   1.69672  54.431084

# **B.Feature engineering**

In [4]:
df['BMI'] = round(df['Weight_kg'] / (df['Height_m'] ** 2), 2)
def age_group(age):
    if age < 30:
        return "<30"
    elif 30 <= age <= 45:
        return "30–45"
    elif 46 <= age <= 60:
        return "46–60"
    else:
        return ">60"
df['AgeGroup'] = df['Age'].apply(age_group)
print(df[['Age', 'BMI', 'AgeGroup']])

   Age    BMI AgeGroup
0   30  18.19    30–45
1   19  18.70      <30
2   45  22.33    30–45
3   22  21.46      <30
4   29  22.02      <30
5   50  18.32    46–60
6   51  20.35    46–60
7   23  19.46      <30
8   17  17.08      <30
9   39  18.91    30–45

# **C.Categorical --> Numerical encoding**

In [5]:
import pandas as pd

frailty_data = pd.read_csv("/content/Problem-1.csv")
frailty_data["Frailty_binary"] = frailty_data["Frailty"].map({"Y": 1, "N": 0}).astype("int8")

if "AgeGroup" in frailty_data.columns:
    frailty_data = pd.get_dummies(frailty_data, columns=["AgeGroup"], prefix="AgeGroup")
frailty_data.to_csv("frailty_data_encoded.csv", index=False)

print(frailty_data.to_string())

   Height  Weight  Age  Grip_strength Frailty  Frailty_binary
0    65.8     112   30             30       N               0
1    71.5     136   19             31       N               0
2    69.4     153   45             29       N               0
3    68.2     142   22             28       Y               1
4    67.8     144   29             24       Y               1
5    68.7     123   50             26       N               0
6    69.8     141   51             22       Y               1
7    70.1     136   23             20       Y               1
8    67.9     112   17             19       N               0
9    66.8     120   39             31       N               0

# **D.EDA&Reporting**

In [15]:
import pandas as pd, os

df["Frailty_binary"] = df["Frailty"].map({"Y": 1, "N": 0}).astype("int8")

summary = df.describe().T[['mean','50%','std']].rename(columns={'50%':'median'})

correlation = df["Grip_strength"].corr(df["Frailty_binary"])

os.makedirs("reports", exist_ok=True)
with open("reports/findings.md","w") as f:
    f.write("# Frailty Dataset Report\n\n")
    f.write("## Summary Statistics\n\n"+summary.to_markdown())
    f.write("\n\n## Correlation\n\n")
    f.write(f"Correlation between Grip_strength and Frailty_binary: {correlation:.3f}")

print(f"Correlation between Grip_strength and Frailty_binary: {correlation:.2f}")

summary

Correlation between Grip_strength and Frailty_binary: -0.48

                 mean  median        std
Height           68.6   68.45   1.670662
Weight          131.9  136.00  14.231811
Age              32.5   29.50  12.860361
Grip_strength    26.0   27.00   4.521553
Frailty_binary    0.4    0.00   0.516398